Remove Debug Cout that causes large output
dyninst/dyninst pull request #1029
Opened 2021-05-11 22:21 UTC by bbiiggppiigg

As title, there is one lingering debug cout that causes large output as mentioned in the issue #1028 

closes #1028

2021-05-12 18:20 UTC, hainest approved these changes

2021-05-14 22:08 UTC, mxz297 requested changes
Do not reuse `DYNINST_DEBUG_PARSING`, which is for ParseAPI, in common.

2021-05-15 03:47 UTC, bbiiggppiigg commented on common/src/debug_common.C
> +    if(getenv("DYNINST_DEBUG_PARSING") || getenv("COMMON_DEBUG_PARSING")){
done as suggested.

2021-05-15 15:10 UTC, mxz297 approved these changes

2021-05-16 05:08 UTC, hainest commented
https://bottle.cs.wisc.edu/search?dyninst_branch=PR1029&since_date=2021-05-14

LGTM.

2021-05-16 05:09 UTC, merged