Lookup functions in the binding table directly
dyninst/dyninst pull request #1337
Opened 2022-12-13 13:14 UTC by Maetveis

instead of making multiple redundant copies of it. Copying and making a map out of the table incurs a significant overhead when the symbol table is large.

This significantly speeds up omnitrace when using `--caller-include` (https://github.com/AMDResearch/omnitrace/pull/202, it makes use of the `caller` method on call points.)

2022-12-13 18:06 UTC, hainest requested changes
I know very little about this aspect of Dyninst, so this question may be completely absurb, but bear with me.

Are these two questions equivalent for all possible parseable entities?

```
If the target address is the target of an entry in the function binding table (unix.C:770)...
If the target address is the target of an entry in the relocation table (Symtab.C:1566)...
```

2022-12-13 20:07 UTC, kupsch commented on symtabAPI/h/Symtab.h
> +    bool findPltEntryByTarget(Address target_address, relocationEntry& result) const;
I agree with not switching to optional now. There are many places in the code where that could be used and we should do consider that change in the future along with the others.

2022-12-14 05:18 UTC, jrmadsen commented on dyninstAPI/src/unix.C
> -   // Do this the hard way - an inter-module jump
Just a quick reminder here, you can hit the settings button and below the "unified" and "split" view options is a hide whitespace box. It cleans up viewing the changes quite nicely.

2022-12-14 12:18 UTC, Maetveis commented
> I know very little about this aspect of Dyninst, so this question may be completely absurb, but bear with me.
> 
> Are these two questions equivalent for all possible parseable entities?
> 
> ```
> If the target address is the target of an entry in the function binding table (unix.C:770)...
> If the target address is the target of an entry in the relocation table (Symtab.C:1566)...
> ```

I am not at all familiar with what these _should_ mean, I was just looking at the current implementation, and I think this patch should introduce NFC.

[`image->getPltFuncs()` returns a map created from `image->getbject()->getFuncBindingTable()`](https://github.com/dyninst/dyninst/blob/d7425515bac9f81ffacfd56af3f301999bb83b31/dyninstAPI/src/image.C#L2114) that function [just returns `relocation_table_`](https://github.com/dyninst/dyninst/blob/18f68ed3aa25a3108fcf89ef8aa132791d289fc2/symtabAPI/src/Symtab.C#L1547).

The extra loop to find the entry in the "function binding table" after the lookup in `pltFuncs` really puzzled me at the start, but I think it's just the original authors didn't realize that these two things are the same in the end. (I don't know if they should be or its a bug that they are, but they are the same before and after this patch)

2022-12-14 12:41 UTC, Maetveis commented on dyninstAPI/src/unix.C
> -   // Do this the hard way - an inter-module jump
Purged the formatting only changes.

2022-12-14 18:26 UTC, hainest commented
We agree this should be a useful change. Did you measure the effect of just this change on the runtime?

2022-12-14 22:11 UTC, hainest commented
No new regressions: https://bottle.cs.wisc.edu//search?dyninst_branch=PR1337

2022-12-15 12:35 UTC, Maetveis commented
> Did you measure the effect of just this change on the runtime?

Yes just now:

<details>
<summary>before (3937542bdc773b6f10740e0746e9c4fb7f8e02d6)</summary>

```plaintext
omnitrace --caller-include "hip.*"  -o    2200.69s user 80.70s system 123% cpu 30:54.51 total

# Samples: 11M of event 'task-clock'
# Event count (approx.): 2263347200000
#
# Children      Self  Command        Shared Object                  Symbol                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
# ........  ........  .............  .............................  ....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
#
    22.61%    22.59%  omnitrace      libdyninstAPI.so.12.2.1        [.] image::getPltFuncs
    21.44%    21.43%  omnitrace      libdyninstAPI.so.12.2.1        [.] block_instance::callee
    16.46%     0.00%  omnitrace      [unknown]                      [.] 0000000000000000
     8.35%     0.00%  omnitrace      [unknown]                      [.] 0x0000000000055b55
     6.60%     0.00%  omnitrace      [unknown]                      [.] 0x0000000000000001
     5.80%     5.78%  omnitrace      libc-2.31.so                   [.] __strncpy_sse2_unaligned
     5.73%     5.70%  omnitrace      libc-2.31.so                   [.] __strcat_sse2_unaligned
     4.70%     0.00%  omnitrace      libgomp.so.1.0.0               [.] 0x00007f7e429b12ee
     4.70%     4.70%  omnitrace      libgomp.so.1.0.0               [.] 0x000000000001d2ee
     4.11%     0.00%  omnitrace      [unknown]                      [.] 0x0000000000000041
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000000000000021d
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186dbb70
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000056491d6502b0
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000056491d650a10
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000056491d654460
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000056491d65b4d0
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000056491d65d4f0
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000056491d671fe0
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000056491d686fe0
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186d9b90
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186da270
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186daa70
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186db090
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186debe0
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186def10
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186dfa20
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186dfbc0
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186e3ae0
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000056491d64e550
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000056491d65d200
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000056491d66b6c0
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000056491d66bf90
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000056491d66f320
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000056491d6707d0
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000056491d67f170
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000056491d685000
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186daf30
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000056491d6493c0
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000056491d65e130
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186dea00
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186d9140
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186d95a0
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186db790
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186df2e0
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186df420
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186df5a0
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186e0510
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186e0cb0
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186e17b0
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x00005649186e1ad0
     3.75%     0.00%  omnitrace      [unknown]                      [.] 0x000056491 [...]

2022-12-15 16:12 UTC, hainest commented
>So omnitrace binary rewrite goes from 30 minutes to 3 minutes on the petsc library!

That is surprising, but very welcome. Thanks for your efforts!

2022-12-15 16:13 UTC, merged