Make MappedFile::mapped_files threadsafe
dyninst/dyninst pull request #1493
Opened 2023-08-19 00:46 UTC by hainest

Currently, a MappedFile is created from a constructor in either the Symtab or Archive classes. In both cases, a user is allowed to invoke them in parallel (although only one thread may enter the constructor), but the cache here is not threadsafe.

2023-08-21 14:41 UTC, kupsch requested changes

2023-08-21 14:41 UTC, kupsch commented on common/src/MappedFile.C
>           ret->refCount++;
This is not thread safe.  Make refCount atomic.

2023-08-21 14:41 UTC, kupsch commented on common/src/MappedFile.C
decrement and then test of `refCount` is not thread safe.  `refCount` needs to be atomic and then and then atomically decrement and return the pre decrement value; and then test the value.

2023-09-20 02:49 UTC, closed without merging

2023-09-20 02:49 UTC, hainest commented
I'm closing this as making the class threadsafe is nearly impossible given the semantics of `setSharing`.