Add RISC-V Symtab API
dyninst/dyninst pull request #1831
Opened 2024-12-06 04:14 UTC by wxrdnx

Added RISC-V register and instruction mnemonic definitions.
Added RISC-V support to the Symtab API so that it can parse and understand RISC-V ELF binaries.

2024-12-17 17:52 UTC, kupsch commented
@wxrdnx, a more descriptive title for the PR and the commit would be `add RISC-V instruction mnemonics and registers`.  You can change the PR title with the `edit` button, and you change the commit using `commit --amend` or interactive rebase and a forced push.

2024-12-19 04:45 UTC, wxrdnx commented
> @wxrdnx, a more descriptive title for the PR and the commit would be `add RISC-V instruction mnemonics and registers`. You can change the PR title with the `edit` button, and you change the commit using `commit --amend` or interactive rebase and a forced push.

All done. The wrong comment in `riscv64_regs.h` is also fixed.

2024-12-19 05:02 UTC, hainest commented
Ah, sorry. I didn't look at this before merging #1842. You'll need to move the ROSE register stuff into dataflowAPI. Let me know if you have any questions.

2024-12-19 05:42 UTC, wxrdnx commented
> Ah, sorry. I didn't look at this before merging #1842. You'll need to move the ROSE register stuff into dataflowAPI. Let me know if you have any questions.

Got it.
Also I have noticed that `DwarfEncToReg` is added to `MachRegister.C`, so I need to add the translation code for Dwarf register.
I'll probably do them tomorrow.

2024-12-19 14:02 UTC, hainest commented
> > Ah, sorry. I didn't look at this before merging #1842. You'll need to move the ROSE register stuff into dataflowAPI. Let me know if you have any questions.
> 
> Got it. Also I have noticed that `DwarfEncToReg` is added to `MachRegister.C`, so I need to add the translation code for RISC-V Dwarf registers. I'll probably do them tomorrow and also rebase my branch to master.

I had thought about that after I commented yesterday, but didn't have a chance to leave a comment. Much like the ROSE translations, I plan to move the DWARF translations out of MachRegister. I'll make a draft PR to do that and wait to merge it until you have time to add the translation tables.

2024-12-20 04:05 UTC, wxrdnx commented
> > > Ah, sorry. I didn't look at this before merging #1842. You'll need to move the ROSE register stuff into dataflowAPI. Let me know if you have any questions.
> > 
> > 
> > Got it. Also I have noticed that `DwarfEncToReg` is added to `MachRegister.C`, so I need to add the translation code for RISC-V Dwarf registers. I'll probably do them tomorrow and also rebase my branch to master.
> 
> I had thought about that after I commented yesterday, but didn't have a chance to leave a comment. Much like the ROSE translations, I plan to move the DWARF translations out of MachRegister. I'll make a draft PR to do that and wait to merge it until you have time to add the translation tables.

I've just added the translation tables, so I think #1845 becomes mergeable.

2024-12-20 04:22 UTC, hainest commented
> > > > Ah, sorry. I didn't look at this before merging #1842. You'll need to move the ROSE register stuff into dataflowAPI. Let me know if you have any questions.
> > > 
> > > 
> > > Got it. Also I have noticed that `DwarfEncToReg` is added to `MachRegister.C`, so I need to add the translation code for RISC-V Dwarf registers. I'll probably do them tomorrow and also rebase my branch to master.
> > 
> > 
> > I had thought about that after I commented yesterday, but didn't have a chance to leave a comment. Much like the ROSE translations, I plan to move the DWARF translations out of MachRegister. I'll make a draft PR to do that and wait to merge it until you have time to add the translation tables.
> 
> I've just added the translation tables, so I think #1845 becomes mergeable.

If I merge that, then you'll need to rebase this PR and move the decode tables out of MachRegister.C and into dataflowAPI/rose/registers. If we merge this PR first, then I can take care of that code motion. Either way works for me. I just don't want to add work for you unnecessarily.

2024-12-20 18:23 UTC, wxrdnx commented
> > > > > Ah, sorry. I didn't look at this before merging #1842. You'll need to move the ROSE register stuff into dataflowAPI. Let me know if you have any questions.
> > > > 
> > > > 
> > > > Got it. Also I have noticed that `DwarfEncToReg` is added to `MachRegister.C`, so I need to add the translation code for RISC-V Dwarf registers. I'll probably do them tomorrow and also rebase my branch to master.
> > > 
> > > 
> > > I had thought about that after I commented yesterday, but didn't have a chance to leave a comment. Much like the ROSE translations, I plan to move the DWARF translations out of MachRegister. I'll make a draft PR to do that and wait to merge it until you have time to add the translation tables.
> > 
> > 
> > I've just added the translation tables, so I think #1845 becomes mergeable.
> 
> If I merge that, then you'll need to rebase this PR and move the decode tables out of MachRegister.C and into dataflowAPI/rose/registers. If we merge this PR first, then I can take care of that code motion. Either way works for me. I just don't want to add work for you unnecessarily.

Okay. I don't think moving the decoder table is a difficult task, so maybe #1845 can be merged first and I'll handle the decoder table on my own.

2025-02-05 03:00 UTC, wxrdnx commented
@kupsch I've fixed the issue you've mentioned in today's meeting.

2025-02-10 23:29 UTC, hainest requested changes
Please add the unit tests from https://github.com/dyninst/unit-tests/pull/14.

For the DWARF registers, we should probably think about aliased registers at some point. I should do the same for arm. This is pretty much never used, so it's not a priority.

2025-02-10 23:29 UTC, hainest commented on common/src/registers/MachRegister.C
> +    if(arch == Arch_riscv64) {
We don't need this check since `getZeroFlag` will return `InvalidReg`. This puts the documentation for riscv in one spot (i.e., in `getZeroFlag`).

2025-02-10 23:29 UTC, hainest commented on common/src/registers/MachRegister.C
> +        return is_vec || is_fpr;
`isFloatingPoint` includes all control/status registers modified or used by FP instructions.

```suggestion
        auto const is_fcsr = (*this == riscv64::fcsr);
        return is_vec || is_fpr || is_fcsr;
```

2025-02-10 23:29 UTC, hainest commented on common/src/registers/MachRegister.C
> +      case Arch_riscv64: {
If Capstone supports them, we should probably include the **un**privileged registers at some point. We don't have to do that now.

2025-02-10 23:29 UTC, hainest commented on common/src/registers/MachRegister.C
> +        return false; // vector currently not supported
Are they in Capstone?

2025-02-10 23:29 UTC, hainest commented on instructionAPI/src/Instruction.C
> +        case Arch_riscv64:
Could you add a blank line above this to visually separate it from the amdgpu ones?

2025-02-13 22:23 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +             case riscv64::GPR: return riscv64::x0;
I thought there were only 32 general-purpose registers (x0~x31) in RISC-V and all their basic registers are mapped to x0?

2025-02-13 22:27 UTC, wxrdnx commented on common/h/registers/riscv64_regs.h
> +  //const int32_t VTR = 0x00040000; // vector registers
Capstone currently does not support vector registers

2025-02-14 04:09 UTC, hainest commented on common/src/registers/MachRegister.C
> +             case riscv64::GPR: return riscv64::x0;
x0 is hardwired to contain only zeros, so I don't think it could serve as even a logical base register for x1-31. There is a lot of chatter in the [manual](https://github.com/riscv/riscv-isa-manual/releases/download/riscv-isa-release-25d7f16-2025-02-11/riscv-unprivileged.pdf) in `2.1. Programmers' Model for Base Integer ISA`, but my primary influence was

```text
For these reasons, we chose a conventional size of 32 integer registers for RV32I.
Dynamic register usage tends to be dominated by a few frequently accessed
registers, and regfile implementations can be optimized to reduce access energy for
the frequently accessed registers (Tseng & Asanović, 2000).
```

Even if the hardware uses register renaming on some smaller register file, the integer registers (GPRs) should not alias each other. Thoughts?

2025-02-14 04:19 UTC, hainest commented on common/h/registers/riscv64_regs.h
> +  //const int32_t VTR = 0x00040000; // vector registers
From my reading, it looks like the Q extension needs D and Zhf needs only F, but neither needs the vector extension. Are the Capstone folks treating Q and Zhf as vector extensions?

2025-02-14 06:01 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +             case riscv64::FPR: return riscv64::f0;
Capstone distinguishes between `f<N>_32` and `f<N>_64`. Dwarf, on the other hand, does not distinguish between the two. In fact, in riscv64, `f<N>_32` is Nan-boxed to `f<N>_64`.

> When multiple floating-point precisions are supported, then valid values of narrower n-bit types,
n<FLEN, are represented in the lower n bits of an FLEN-bit NaN value, in a process termed NaN-
boxing. The upper bits of a valid NaN-boxed value must be all 1s. Valid NaN-boxed n-bit values
therefore appear as negative quiet NaNs (qNaNs) when viewed as any wider m-bit value, n < m ≤ FLEN.
Any operation that writes a narrower result to an 'f' register must write all 1s to the uppermost FLEN-n
bits to yield a legal NaN-boxedvalue

So when accessing f0_32, you are actually accessing the entire register, not only just half of it. Therefore, I introduced `f<N>` since there is no need to distinguish between `f<N>_32` and `f<N>_64`.

f<N>_32` and `f<N>_64` exist only because Capstone differentiate the two. Personally, I prefer using `f<N>`  because it feels more succinct compared to `f<N>_64`. What do you think?

2025-02-14 06:06 UTC, wxrdnx commented on common/h/registers/riscv64_regs.h
> +  //const int32_t VTR = 0x00040000; // vector registers
It is true that Q depends on D and Zhf depends on F but not on D.

Capstone folks only supports I (Integer), M (Multiplication), A (Atomic), F (Floating Points), D (Double Floating Points), and C (Compressed) extensions. Q extension, Zhf extension, and vector extensions are all not supported.

2025-02-14 06:17 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +        return false; // vector currently not supported
No

2025-02-14 06:20 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +      case Arch_riscv64: {
Unfortunately Capstone does not support them

2025-02-14 06:22 UTC, wxrdnx commented on instructionAPI/src/Instruction.C
> +        case Arch_riscv64:
Fixed

2025-02-14 06:24 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +    if(arch == Arch_riscv64) {
Fixed

2025-02-14 06:28 UTC, wxrdnx commented on common/h/registers/riscv64_regs.h
> +  DEF_REGISTER(        a0,  10 | GPR | Arch_riscv64, "riscv64");
Ok. Should I add aliases for `f<N>` registers only or all `f<N>`, `f<N>_32`, and `f<N>_64`? (See [#discussion_r1955600709](discussion_r1955600709))

2025-02-14 06:44 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +             case riscv64::GPR: return riscv64::x0;
Interesting. My view point is that `baseRegister(x<N>) = x<0>` because in terms of register opcode encoding, x<N> is indeed encoded to N, so naturally the base register of x<N> can be thought of as x0, kind of like isomorphism. Personally I think Register File is a low-level, hardware implementation stuff. It has little to do with this matter.

2025-02-14 06:50 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +        return is_vec || is_fpr;
Fixed

2025-02-14 13:49 UTC, hainest commented on common/h/registers/riscv64_regs.h
> +  //const int32_t VTR = 0x00040000; // vector registers
Thanks for the details.

2025-02-14 14:30 UTC, hainest commented on common/src/registers/MachRegister.C
> +             case riscv64::GPR: return riscv64::x0;
Oooh, sorry. This has been a complete miscommunication on my part. A base register is a register that contains some other named register. The main use for this is to know if two instructions write to the same location.

On x86,
```asm
mov  al, 0x1
mov rax, 0x2
```

Here the two registers have different names, but the value is written to the same location such that reading `al` after the second instruction would return `0x2` because `ah` refers to bits 0 to 7 of `rax`. In this case, we need to make sure `ah.getBaseRegister() == rax.getBaseRegister()`.

Contrastingly on RISC-V,
```asm
addi x1, x0, 0x1
addi x2, x0, 0x2
```

A read of `x1` after the second instruction would still return 0x1, so we need to make sure `x1.getBaseRegister() != x2.getBaseRegister()`.

Does that help clarify? :smiley: 

---

This is an aside, but something that caught my attention. I just noticed that the 32-bit RV32I registers seem to alias the 64-bit registers, even though they have identical names. For example,

```text
LUI (load upper immediate) uses the same opcode as RV32I. LUI
places the 32-bit U-immediate into register rd, filling in the lowest
12 bits with zeros. The 32-bit result is sign-extended to 64 bits.
```

This seems to suggest that `x1.getSize() == 4` for RVI32, but is 8 for RVI64 even though they are the same register name. I'm assuming this is part of the portability goal to have one binary run on both RVI32 and RVI64. I don't think this would affect our calculation of the base register, but might cause Dyninst to run into issues if it checks the size of the register instead of checking the base register. This is akin to ppc32 vs ppc64, but we do a terrible job of separating those two architectures. Maybe we don't need to worry about this right now.

2025-02-14 14:48 UTC, hainest commented on common/src/registers/MachRegister.C
> +             case riscv64::FPR: return riscv64::f0;
> Capstone distinguishes between `f<N>_32` and `f<N>_64`. Dwarf, on the other hand, does not distinguish between the two. In fact, in riscv64, `f<N>_32` is Nan-boxed to `f<N>_64`.
> 
> > When multiple floating-point precisions are supported, then valid values of narrower n-bit types,
> > n<FLEN, are represented in the lower n bits of an FLEN-bit NaN value, in a process termed NaN-
> > boxing. The upper bits of a valid NaN-boxed value must be all 1s. Valid NaN-boxed n-bit values
> > therefore appear as negative quiet NaNs (qNaNs) when viewed as any wider m-bit value, n < m ≤ FLEN.
> > Any operation that writes a narrower result to an 'f' register must write all 1s to the uppermost FLEN-n
> > bits to yield a legal NaN-boxedvalue

I have no idea how I missed that. Though I have to say they really twisted themselves into knots to minify FP support here. I've never seen anything like this before.

> So when accessing f0_32, you are actually accessing the entire register, not only just half of it. Therefore, I introduced `f<N>` since there is no need to distinguish between `f<N>_32` and `f<N>_64`.

Agreed. We should also explicitly make `f<N>_32` and `f<N>_64` alias `f<N>` in `riscv_regs.h`. Then we can just check `f<N>` here.

> `f<N>_32` and `f<N>_64` exist only because Capstone differentiate the two. Personally, I prefer using `f<N>` because it feels more succinct compared to `f<N>_64`. What do you think?

I think `f<N>` is a good approach. I would add some comments as to why we're doing it that way.

2025-02-14 14:51 UTC, hainest commented on common/h/registers/riscv64_regs.h
> +  DEF_REGISTER(        a0,  10 | GPR | Arch_riscv64, "riscv64");
If we alias `f<N>_32` and `f<N>_64` to `f<N>`, then we can just have the ABI registers alias `f<N>`.

2025-02-15 02:48 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +             case riscv64::GPR: return riscv64::x0;
Oh sorry I misunderstood the meaning of base registers. If that's the case, I'll just simply map all GPRs and FPRs to itself

```c
case Arch_riscv64:
   return *this;
```

is that ok?
---
Since I'm focusing on RI64 right now, I don't worry too much about stuff related to RI32.

2025-02-15 03:09 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +             case riscv64::FPR: return riscv64::f0;
The comments in `riscv64_regs.h`, which I wrote in the past before I knew about the Nan-boxed thing, were indeed confusing. I updated the comments in that file.

2025-02-15 03:34 UTC, wxrdnx commented on common/h/registers/riscv64_regs.h
> +  DEF_REGISTER(        ra,   1 | GPR | Arch_riscv64, "riscv64");
AFAIK the "alternate link register" is used for implementing millicode routines, particularly prologue/epilogue routine mentioned in [Waterman's thesis](https://people.eecs.berkeley.edu/~krste/papers/EECS-2016-1.pdf) on page 66 ~ 67.
It seems that the intention of function prologue/epilogue routines mentioned in that paper is to reduce the overall code size by implementing the function prologues/epilogues as a function subroutine itself. However, since we are dealing with `x1`(`ra`) in the function prologue/epilogue, we use `x5`(`t0`) instead of `x1`(`ra`) to call the function prologue/epilogue function routine in order to avoid register conflicts.
This is very interesting, and if I ever find myself seeing it in the wild, I'll definitely take notes of it. Regardless, based on the examples he gave in his paper, I don't think we should make `ra` an alias for `x5`.

2025-02-15 03:38 UTC, wxrdnx commented on common/h/registers/riscv64_regs.h
> +  DEF_REGISTER(        a0,  10 | GPR | Arch_riscv64, "riscv64");
Updated

2025-02-15 16:23 UTC, hainest commented on common/src/registers/MachRegister.C
> +             case riscv64::GPR: return riscv64::x0;
This should be fine once we have the aliases in place.

2025-02-15 16:41 UTC, hainest commented on common/src/registers/MachRegister.C
> +             case riscv64::FPR: return riscv64::f0;
After a bit more consideration, I think we can just eliminate the 64/32 suffixed versions and just directly map both Capstone representations to the `f<N>` inside the instruction decoder. That would save us some cognitive load without losing any information. Thoughts?

2025-02-15 16:43 UTC, hainest commented on common/h/registers/riscv64_regs.h
> +  DEF_REGISTER(        ra,   1 | GPR | Arch_riscv64, "riscv64");
Let me read over this some more. The more I get to know RISCV, the less I understand why people like it so much. I've never seen anything add so much complexity to save a few transistors.

2025-02-17 00:06 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +             case riscv64::GPR: return riscv64::x0;
Fixed

2025-02-21 15:57 UTC, hainest commented on common/h/registers/riscv64_regs.h
> +  DEF_REGISTER(        ra,   1 | GPR | Arch_riscv64, "riscv64");
At the time of Waterman's thesis, there didn't seem to be a convention for calling millicode routines. I think x5 has become that convention, but I agree we should probably leave that out for now. We should include `ra` as an alias for `x1` and `sp` as an alias for `x2`.

2025-02-22 03:12 UTC, wxrdnx commented on common/h/registers/riscv64_regs.h
> +  DEF_REGISTER(        ra,   1 | GPR | Arch_riscv64, "riscv64");
Okay.
But my question is: If I change `riscv64::ra` aliasa to `riscv64::x5`, wouldn't that make `riscv64::ra` ambiguous?

2025-06-20 20:06 UTC, wxrdnx commented
Hi @kupsch and @hainest:

I think this PR is ready to review.
The only testers that does not pass are the Libabigail ones. This is because 1. RISC-V mnemonics are added, 2. Code that parses RISC-V specific sections are also added to the objectELF class.

2025-06-24 17:39 UTC, wxrdnx commented
Hi @kupsch and @hainest:

I've removed the RISC-V unit test in this PR, and I'm going to move it to another separate PR.

2025-06-24 23:41 UTC, hainest commented
> Hi @kupsch and @hainest:
> 
> I've removed the RISC-V unit test in this PR, and I'm going to move it to another separate PR.

I'd rather have the unit tests here so we can run them during the CI for this PR.

To keep this PR more constrained, I would prefer the ELF parsing be moved to a separate PR. Naturally, it will be dependent on this one.

2025-07-12 01:05 UTC, wxrdnx commented
@hainest 
I've moved the ELF parsing to a separate PR
I've also added unit tests in this PR

2025-07-14 12:03 UTC, hainest commented
> @hainest
> 
> I've moved the ELF parsing to a separate PR #1966 I've also added unit tests in this PR

Thanks for making the suggested updates. 

> The only testers that does not pass are the Libabigail ones. This is because

If you add the ABI-BREAKER label, the libabigail tests won't run.

---

On first glance, this seems to be good. I'll take a deeper look in the next few days. If Jim approves them first, let's merge. I don't want to delay your progress any further.

2025-07-21 15:12 UTC, hainest commented on common/h/registers/riscv64_regs.h
> +  DEF_REGISTER(        ra,   1 | GPR | Arch_riscv64, "riscv64");
Aliases need to be declared with [`DEF_REGISTER_ALIAS`](https://github.com/dyninst/dyninst/blob/master/common/h/registers/reg_def.h#L59) so that `riscv64::ra == riscv64::x5` is always true.

2025-07-21 15:43 UTC, hainest commented on common/src/registers/MachRegister.C
> +      case Arch_riscv64: return riscv64::a7;
I didn't see this in The ISA manual (20240411). Did it come from the linux kernel source? If so, could we add a link for reference?

2025-07-21 16:17 UTC, hainest commented on instructionAPI/src/syscalls.C
> +    return id == riscv64_op_ecall;
What about ebreak?

2025-07-21 16:32 UTC, hainest commented on common/h/registers/riscv64_regs.h
> +  DEF_REGISTER(     f0_32,   0 | FPR | Arch_riscv64, "riscv64");
`f<N>_32` and `f<N>_64` should be declared with DEF_REGISTER_ALIAS to make them explicit aliases.

2025-07-21 16:33 UTC, hainest commented on tests/unit/MachRegister/base_registers/riscv64.cpp
> +  BASEREG_CHECK(riscv64::f0, riscv64::f0);
These are actually alias checks (see my comments for riscv64_regs.h).

2025-07-22 19:22 UTC, wxrdnx commented
> Have you encountered any serious parsing issues due to the absence of ROSE data? It looks like even the most recent version of ROSE still doesn't have any riscv64 stuff.

ROSE does not support RISC-V unfortunately, so the RISC-V ROSE files were written by me, similar to the AMDGPU ROSE files. Since RISC-V is not supported by ROSE, we're using [SAIL](https://github.com/riscv/sail-riscv) as our instruction semantics. However, SAIL is written in Ocaml, meaning that it is extremely difficult for Dyninst to use the information directly. Thus, I've written scripts that convert SAIL to ROSE C++ class, and those scripts will come later.

> I'm a bit confused. This adds ROSE registers in external/rose/riscv64InstructionEnum.h, but the ExpressionConversionVisitor doesn't implement any expansion for them. Will that come later?

Yes, they will come later. Do you think they should also go in this PR?

> Will instruction [categories](https://github.com/dyninst/dyninst/blob/master/instructionAPI/src/Instruction.C#L428) be added in the instruction decoding PR?

Yes, they will in the future

> It looks like the ELF stuff was extracted into [1966](https://github.com/dyninst/dyninst/pull/1966). Should this be removed here?

Sorry, I'm not sure what "this" means here. Do you want me to move all files in `symtabAPI` to #1966 ?

2025-07-23 05:07 UTC, hainest commented
> > Have you encountered any serious parsing issues due to the absence of ROSE data? It looks like even the most recent version of ROSE still doesn't have any riscv64 stuff.
> 
> ROSE does not support RISC-V unfortunately, so the RISC-V ROSE files were written by me, similar to the AMDGPU ROSE files. Since RISC-V is not supported by ROSE, we're using [SAIL](https://github.com/riscv/sail-riscv) as our instruction semantics. However, SAIL is written in Ocaml, meaning that it is extremely difficult for Dyninst to use the information directly. Thus, I've written scripts that convert SAIL to ROSE C++ class, and those scripts will come later.

What a pain. It's good you were able to get it working. 

> > I'm a bit confused. This adds ROSE registers in external/rose/riscv64InstructionEnum.h, but the ExpressionConversionVisitor doesn't implement any expansion for them. Will that come later?
> 
> Yes, they will come later. Do you think they should also go in this PR?

No, they should go in a separate PR.
 
> > Will instruction [categories](https://github.com/dyninst/dyninst/blob/master/instructionAPI/src/Instruction.C#L428) be added in the instruction decoding PR?
> 
> Yes, they will in the future

:+1: 

> > It looks like the ELF stuff was extracted into [1966](https://github.com/dyninst/dyninst/pull/1966). Should this be removed here?
> 
> Sorry, I'm not sure what "this" means here. Do you want me to move all files in `symtabAPI` to #1966 ?

Yeah, let's move the symtab stuff into 1966. That way it's all in one place to make it easier to review.

2025-07-24 19:18 UTC, wxrdnx commented
> Yeah, let's move the symtab stuff into 1966. That way it's all in one place to make it easier to review.
Done!

2025-07-25 13:53 UTC, hainest commented on common/src/registers/MachRegister.C
> +      case Arch_riscv64: return riscv64::a7;
Did you have a chance to check on this one?

2025-07-25 13:54 UTC, hainest commented on instructionAPI/src/syscalls.C
> +    return id == riscv64_op_ecall;
Did you have a chance to check on this one?

The RISC-V Instruction Set Manual Volume I
Version 20240411
2.8. Environment Call and Breakpoints

2025-08-21 23:29 UTC, hainest commented
@wxrdnx Have you had a chance to take a look at the two items I mentioned? [1](https://github.com/dyninst/dyninst/pull/1831#discussion_r2219583399), [2](https://github.com/dyninst/dyninst/pull/1831#discussion_r2219660929). No rush. With just two small items to go, we could get this merged and let you move on to more important things.

2025-08-26 03:20 UTC, wxrdnx commented
> @wxrdnx Have you had a chance to take a look at the two items I mentioned? [1](https://github.com/dyninst/dyninst/pull/1831#discussion_r2219583399), [2](https://github.com/dyninst/dyninst/pull/1831#discussion_r2219660929). No rush. With just two small items to go, we could get this merged and let you move on to more important things.

Hi @hainest :

For [1](https://github.com/dyninst/dyninst/pull/1831#discussion_r2219583399), the syscall calling convention is nowhere defined in the ISA manual. [This discussion](https://github.com/riscv-non-isa/riscv-elf-psabi-doc/issues/13) says that the syscall nr is OS-specific. For Linux, the syscall nr is defined in the [source code](https://elixir.bootlin.com/linux/v6.15.7/source/arch/riscv/include/asm/syscall.h#L27-L31), which is `a7`. I'm not sure if Dyninst runs on FreeBSD, but for FreeBSD, the syscall nr can be seen from [the FreeBSD Manual](https://man.freebsd.org/cgi/man.cgi?apropos=0&manpath=Debian+13.0.0&query=syscall&sektion=2) (scroll down to the `Architecture calling conventions` section). It is also `a7`.

For [2](https://github.com/dyninst/dyninst/pull/1831#discussion_r2219660929), `ecall` is the RISC-V equivalent of `int 0x80` in x86 or `syscall` in x86_64, while `ebreak` is the RISC-V equivalent of `int3` in x86. `ebreak` is used to generate a breakpoint exception, not to perform syscall. Like `int3`, `ebreak` triggers a user-mode trap, transferring the control to a trap handler, so `ebreak` does not go through the kernel in the same way `ecall` does. Thus, I don't think `ebreak` qualifies as a syscall. 

Source: section 2.8 of the [RISC-V Instruction Set Manual Volume I: Unprivileged ISA](https://drive.google.com/file/d/1uviu1nH-tScFfgrovvFCrj7Omv8tFtkp/view):

> EBREAK was primarily designed to be used by a debugger to cause execution to stop and fall back into the debugger. EBREAK is also used by the standard gcc compiler to mark code paths that should not be executed.

2025-08-26 03:51 UTC, hainest commented
> > @wxrdnx Have you had a chance to take a look at the two items I mentioned? [1](https://github.com/dyninst/dyninst/pull/1831#discussion_r2219583399), [2](https://github.com/dyninst/dyninst/pull/1831#discussion_r2219660929). No rush. With just two small items to go, we could get this merged and let you move on to more important things.
> 
> Hi @hainest :
> 
> For [1](https://github.com/dyninst/dyninst/pull/1831#discussion_r2219583399), the syscall calling convention is nowhere defined in the ISA manual. [This discussion](https://github.com/riscv-non-isa/riscv-elf-psabi-doc/issues/13) says that the syscall nr is OS-specific. For Linux, the syscall nr is defined in the [source code](https://elixir.bootlin.com/linux/v6.15.7/source/arch/riscv/include/asm/syscall.h#L27-L31), which is `a7`.

Could you add a link to the linux kernel source with a comment that a7 isn't uniform across all OSes? That sounds like a real pain that I hope we never have to deal with.

> I'm not sure if Dyninst runs on FreeBSD, but for FreeBSD, the syscall nr can be seen from [the FreeBSD Manual](https://man.freebsd.org/cgi/man.cgi?apropos=0&manpath=Debian+13.0.0&query=syscall&sektion=2) (scroll down to the `Architecture calling conventions` section). It is also `a7`.

I would be surprised if the FreeBSD-specific parts of Dyninst have been compiled in the last decade, so I'd say 'no'.

> 
> For [2](https://github.com/dyninst/dyninst/pull/1831#discussion_r2219660929), `ecall` is the RISC-V equivalent of `int 0x80` in x86 or `syscall` in x86_64, while `ebreak` is the RISC-V equivalent of `int3` in x86. `ebreak` is used to generate a breakpoint exception, not to perform syscall. Like `int3`, `ebreak` triggers a user-mode trap, transferring the control to a trap handler, so `ebreak` does not go through the kernel in the same way `ecall` does. Thus, I don't think `ebreak` qualifies as a syscall.
> 
> Source: section 2.8 of the [RISC-V Instruction Set Manual Volume I: Unprivileged ISA](https://drive.google.com/file/d/1uviu1nH-tScFfgrovvFCrj7Omv8tFtkp/view):
> 
> > EBREAK was primarily designed to be used by a debugger to cause execution to stop and fall back into the debugger. EBREAK is also used by the standard gcc compiler to mark code paths that should not be executed.

Derp. I have no idea how I missed that in the docs. Since it is technically a software interrupt, let's add it to [isSoftwareInterrupt](https://github.com/dyninst/dyninst/blob/v13.0.0/instructionAPI/src/interrupts.C).

2025-08-26 15:44 UTC, wxrdnx commented
Hi @hainest :

> Could you add a link to the linux kernel source with a comment that a7 isn't uniform across all OSes? That sounds like a real pain that I hope we never have to deal with.

Done.

> Derp. I have no idea how I missed that in the docs. Since it is technically a software interrupt, let's add it to [isSoftwareInterrupt](https://github.com/dyninst/dyninst/blob/v13.0.0/instructionAPI/src/interrupts.C).

Done.

2025-08-26 18:39 UTC, hainest approved these changes
LGTM. Thanks so much for putting up with all of the questions and edits.

@kupsch Any thoughts?

2025-08-26 19:10 UTC, wxrdnx commented on tests/MachRegister/base_registers/riscv64.cpp
> +
@hainest 
Is the unit test okay?
Do I need to add/delete anything?

2025-08-26 19:10 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +      case Arch_riscv64: return riscv64::a7;
Yes, from the [linux kernel source](https://elixir.bootlin.com/linux/v6.15.7/source/arch/riscv/include/asm/syscall.h#L27-L31).

2025-08-26 19:10 UTC, wxrdnx commented on instructionAPI/src/syscalls.C
> +    return id == riscv64_op_ecall;
`ebreak` is the equivalent of `int3` in x64. It is not used to perform syscall.

2025-08-26 19:10 UTC, wxrdnx commented on common/h/registers/riscv64_regs.h
> +  DEF_REGISTER(     f0_32,   0 | FPR | Arch_riscv64, "riscv64");
Got it, now they're declared using `DEF_REGISTER_ALIAS`.

2025-08-26 19:10 UTC, wxrdnx commented on tests/unit/MachRegister/base_registers/riscv64.cpp
> +  BASEREG_CHECK(riscv64::f0, riscv64::f0);
Got it, Now they're changed to alias checks.

2025-08-26 19:10 UTC, wxrdnx commented on instructionAPI/src/syscalls.C
> +    return id == riscv64_op_ecall;
Checked

> EBREAK was primarily designed to be used by a debugger to cause execution to stop and
fall back into the debugger. EBREAK is also used by the standard gcc compiler to mark
code paths that should not be executed.

So `ebreak` isn't used for syscalls. It is used to fallback into the debugger.

2025-08-26 19:10 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +      case Arch_riscv64: return riscv64::a7;
@hainest  Unfortunately I just figured out that the syscall calling convention is not defined in the doc. (See [this discussion](https://github.com/riscv-non-isa/riscv-elf-psabi-doc/issues/13))

TLDR: the syscall nr is OS-specific, and Linux chooses `a7` ~while FreeBSD chooses `t0`~.

FreeBSD also use `a7`. See [the FreeBSD Manual](https://man.freebsd.org/cgi/man.cgi?apropos=0&manpath=Debian+13.0.0&query=syscall&sektion=2), scroll down to the `Architecture calling conventions` section

2025-08-26 19:24 UTC, wxrdnx commented
@hainest @kupsch 

I did not know that if I comment directly instead of quote reply, the comments are in pending state.
I need to click "Review Changes" -> "Submit Review" to submit the review.
No wonder you can't see my comments month ago.
Guess I've learned something every day.

2025-08-26 20:19 UTC, hainest commented on tests/MachRegister/base_registers/riscv64.cpp
> +
These look fine. I don't think it's necessary to test every register.

2025-08-26 20:21 UTC, hainest commented
> @hainest @kupsch
> 
> I did not know that if I comment directly instead of quote reply on "Files Changed", the comments are in pending state. I need to click "Review Changes" -> "Submit Review" to submit the review. No wonder you can't see my comments months ago. Guess I've learned something every day.

Ah, I was curious about that. You have to resubmit every time. It's the price that is paid so you don't have to do the entire review all at once.

2025-08-28 21:47 UTC, kupsch reviewed
Several comments that should be adjusted and then changes around SPRs.

2025-08-28 21:47 UTC, kupsch commented on common/src/registers/MachRegister.C
> +      // https://elixir.bootlin.com/linux/v6.15.7/source/arch/riscv/include/asm/syscall.h#L27-L31
You can remove this comment and add the following to the top of the function

```
// The syscall register for all platforms can be found in the 
// linux syscall(2) man page.
```

2025-08-28 21:47 UTC, kupsch commented on external/rose/riscv64InstructionEnum.h
> +
Delete this as git records who added the code and when.

```suggestion
```

2025-08-28 21:47 UTC, kupsch commented on common/h/registers/riscv64_regs.h
> +  DEF_REGISTER(   instret,  11 | SPR | Arch_riscv64, "riscv64");
You should move these 3 after `fcsr` as these are all `CSR addresses`. Perhaps these 3 and `fflags`, `frm`, `fcsr` should be there own `CSR` class?  @hainest what do you think?

2025-08-28 21:47 UTC, kupsch commented on common/src/registers/MachRegister.C
> +        return *this;
The base of `fflags` and `frm` should be `fcsr`, as `fcsr` contains these other two registers.

2025-08-28 21:47 UTC, kupsch commented on common/src/registers/MachRegister.C
> +      case Arch_riscv64: // RISC-V does not have flag registers
for consistency remove the comment or add a blank line before `Arch_aarch32` and the comment `// These Architecture do not have a zero flag:`

2025-08-28 21:47 UTC, kupsch commented on common/src/registers/MachRegister.C
> +      case Arch_riscv64: return false; // RISC-V does not have flag registers
`fcsr` and `fflags` are flags.

2025-08-28 21:47 UTC, kupsch commented on common/src/registers/MachRegister.C
> +        auto const is_fcsr = (*this == riscv64::fcsr);
Also `fflags` and `frm`?

2025-08-28 21:47 UTC, kupsch commented on common/src/registers/MachRegister.C
> +        return false; // csrs currently not supported
Since you define the register you should add them here.  All the `SPR`s except `PC`?

2025-08-29 00:23 UTC, hainest commented on common/h/registers/riscv64_regs.h
> +  DEF_REGISTER(   instret,  11 | SPR | Arch_riscv64, "riscv64");
I don't have any strong opinions. If adding a `CSR` class would simplify or enrich the `MachRegister` properties, then it would be a good idea.

2025-08-29 18:00 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +      // https://elixir.bootlin.com/linux/v6.15.7/source/arch/riscv/include/asm/syscall.h#L27-L31
Done

2025-08-29 18:08 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +      case Arch_riscv64: // RISC-V does not have flag registers
Done

2025-08-29 18:28 UTC, wxrdnx commented on common/h/registers/riscv64_regs.h
> +  DEF_REGISTER(   instret,  11 | SPR | Arch_riscv64, "riscv64");
I agree they should be their own class.
I think I should also add the performance-monitoring registers (hpmcounterNN), as they are also unprivileged CSRs.

2025-08-29 18:56 UTC, wxrdnx commented on common/h/registers/riscv64_regs.h
> +  DEF_REGISTER(   instret,  11 | SPR | Arch_riscv64, "riscv64");
Update: I added all unprivileged CSRs mentioned in The RISC-V Instruction Set Manual: Volume II Privileged Architecture, Section 2.2, regardless of whether Capstone supports it or not. (except for those end in "h", which are only used in RV32).

2025-08-29 18:58 UTC, wxrdnx commented on common/h/registers/riscv64_regs.h
> +
Add CSR register group
```suggestion
const int32_t CSR = 0x00100000; // control and status registers
```

2025-08-29 19:01 UTC, wxrdnx commented on common/h/registers/riscv64_regs.h
> +  DEF_REGISTER(   instret,  11 | SPR | Arch_riscv64, "riscv64");
Added all unprivileged CSRs mentioned in The RISC-V Instruction Set Manual: Volume II Privileged Architecture, Section 2.2:
```suggestion
  DEF_REGISTER(           pc,   0 | SPR | Arch_riscv64, "riscv64");

  // From The RISC-V Instruction Set Manual: Volume II Privileged Architecture, Section 2.2
  DEF_REGISTER(       fflags,   0 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(          frm,   1 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(         fcsr,   2 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(       vstart,   3 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(        vxsat,   4 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(         vxrm,   5 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(         vcsr,   6 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(           vl,   7 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(        vtype,   8 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(        vlenb,   9 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(          ssp,  10 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(         seed,  11 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(          jvt,  12 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(        cycle,  13 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(         time,  14 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(      instret,  15 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(  hpmcounter3,  16 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(  hpmcounter4,  17 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(  hpmcounter5,  18 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(  hpmcounter6,  19 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(  hpmcounter7,  20 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(  hpmcounter8,  21 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(  hpmcounter9,  22 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter10,  23 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter11,  24 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter12,  25 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter13,  26 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter14,  27 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter15,  28 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter16,  29 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter17,  30 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter18,  31 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter19,  32 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter20,  33 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter21,  34 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter22,  35 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter23,  36 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter24,  37 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter25,  38 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter26,  39 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter27,  40 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter28,  41 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter29,  42 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter30,  43 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter31,  44 | CSR | Arch_riscv64, "riscv64");
  // RV32 only
  DEF_REGISTER(       cycleh,  45 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(        timeh,  46 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(     instreth,  47 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter3h,  48 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter4h,  49 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter5h,  50 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter6h,  51 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter7h,  52 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter8h,  53 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER( hpmcounter9h,  54 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter10h,  55 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter11h,  56 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter12h,  57 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter13h,  58 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter14h,  59 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter15h,  60 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter16h,  61 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter17h,  62 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter18h,  63 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter19h,  64 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter20h,  65 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter21h,  66 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter22h,  67 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter23h,  68 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter24h,  69 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter25h,  70 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter26h,  71 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter27h,  72 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter28h,  73 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter29h,  74 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter30h,  75 | CSR | Arch_riscv64, "riscv64");
  DEF_REGISTER(hpmcounter31h,  76 | CSR | Arch_riscv64, "riscv64");
```

2025-08-29 19:10 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +        return *this;
Makes sense

2025-08-29 19:10 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +        return *this;
```suggestion
      case Arch_riscv64: {
        if(*this == riscv64::fflags || *this == riscv64::frm) {
          return riscv64::fcsr;
        }
        return *this;
      }
```

2025-08-29 19:12 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +      case Arch_riscv64: return false; // RISC-V does not have flag registers
```suggestion
      case Arch_riscv64: return regC == riscv64::fflags || regC == riscv64::fcsr;
```

2025-08-29 19:15 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +        auto const is_fcsr = (*this == riscv64::fcsr);
Makes sense.
```suggestion
        auto const is_fcsr = (*this == riscv64::fflags) || (*this == riscv64::frm) || (*this == riscv64::fcsr);
```

2025-08-29 19:18 UTC, kupsch commented on common/src/registers/MachRegister.C
> +      case Arch_riscv64: return false; // RISC-V does not have flag registers
sure

2025-08-29 19:18 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +        return false; // csrs currently not supported
```suggestion
        return category == riscv64::CSR;
```

2025-08-29 19:39 UTC, wxrdnx reviewed
I've moved the CSRs to its own category.
Just one question: Some CSR registers that end in "h" (e.g. `cycleh`, `timeh`) are for RV32 only. Should I also include them?

2025-08-29 20:31 UTC, kupsch commented
I don't think that it would hurt to add them.  You should add a comment that they are RV32 only.

2025-08-29 22:10 UTC, wxrdnx commented
> I don't think that it would hurt to add them. You should add a comment that they are RV32 only.

Got it.
Can you review the suggestions?
Does the code look good to you?

2025-09-03 13:41 UTC, wxrdnx commented
@kupsch 
I have sorted CSR registers according to their value instead of their appearance in which they appear in the ISA manual.
I have also added CSR register values as comments.

2025-09-03 15:20 UTC, kupsch commented on common/h/registers/riscv64_regs.h
> +
Add the floating point register aliases also:

```suggestion

  // Floating point register aliases
  DEF_REGISTER_ALIAS(   ft0,  f0, "riscv64");
  DEF_REGISTER_ALIAS(   ft1,  f1, "riscv64");
  DEF_REGISTER_ALIAS(   ft2,  f2, "riscv64");
  DEF_REGISTER_ALIAS(   ft3,  f3, "riscv64");
  DEF_REGISTER_ALIAS(   ft4,  f4, "riscv64");
  DEF_REGISTER_ALIAS(   ft5,  f5, "riscv64");
  DEF_REGISTER_ALIAS(   ft6,  f6, "riscv64");
  DEF_REGISTER_ALIAS(   ft7,  f7, "riscv64");
  DEF_REGISTER_ALIAS(   fs0,  f8, "riscv64");
  DEF_REGISTER_ALIAS(   fs1,  f9, "riscv64");
  DEF_REGISTER_ALIAS(   fa0, f10, "riscv64");
  DEF_REGISTER_ALIAS(   fa1, f11, "riscv64");
  DEF_REGISTER_ALIAS(   fa2, f12, "riscv64");
  DEF_REGISTER_ALIAS(   fa3, f13, "riscv64");
  DEF_REGISTER_ALIAS(   fa4, f14, "riscv64");
  DEF_REGISTER_ALIAS(   fa5, f15, "riscv64");
  DEF_REGISTER_ALIAS(   fa6, f16, "riscv64");
  DEF_REGISTER_ALIAS(   fa7, f17, "riscv64");
  DEF_REGISTER_ALIAS(   fs2, f18, "riscv64");
  DEF_REGISTER_ALIAS(   fs3, f19, "riscv64");
  DEF_REGISTER_ALIAS(   fs4, f20, "riscv64");
  DEF_REGISTER_ALIAS(   fs5, f21, "riscv64");
  DEF_REGISTER_ALIAS(   fs6, f22, "riscv64");
  DEF_REGISTER_ALIAS(   fs7, f23, "riscv64");
  DEF_REGISTER_ALIAS(   fs8, f24, "riscv64");
  DEF_REGISTER_ALIAS(   fs9, f25, "riscv64");
  DEF_REGISTER_ALIAS(  fs10, f26, "riscv64");
  DEF_REGISTER_ALIAS(  fs11, f27, "riscv64");
  DEF_REGISTER_ALIAS(   ft8, f28, "riscv64");
  DEF_REGISTER_ALIAS(   ft9, f29, "riscv64");
  DEF_REGISTER_ALIAS(  ft10, f30, "riscv64");
  DEF_REGISTER_ALIAS(  ft11, f31, "riscv64");
```

2025-09-03 15:54 UTC, kupsch commented on instructionAPI/capstone/riscv64/mnemonics.py
Add the dyninst copyright header

2025-09-03 15:54 UTC, kupsch commented on instructionAPI/capstone/riscv64/registers.py
Add the dyninst copyright header

2025-09-03 16:03 UTC, kupsch commented on common/src/registers/MachRegister.C
> +      // linux syscall(2) man page.
move this comment to the function definition or at the beginning of the body (before the `switch`) as it applies to all architecture.

2025-09-03 16:17 UTC, kupsch commented on common/h/registers/riscv64_regs.h
> +  // Unprivileged Vector CSRs, read/write
Adding a blank line before comments that start a new section would make this more readable. Same thing applies to many other places in this file.

2025-09-03 16:28 UTC, kupsch commented on common/h/registers/riscv64_regs.h
> +  // From The RISC-V Instruction Set Manual: Volume II Privileged Architecture, Section 2.2
Add the manual version number as there are and will be many versions of this document, also a comment describing the comment
```suggestion
  // Control Status Registers (CSRs) - the comment after each is its CSR Id
  // From The RISC-V Instruction Set Manual: Volume II Privileged Architecture,
  // Version 20250805, Section 2.2
```

2025-09-03 16:32 UTC, kupsch commented on common/h/registers/riscv64_regs.h
> +  // f<N>_32 and f<N>_64 are both aliases of f<N>
Try to keep lines that are just comments to 80 columns, and no need to have each sentence be on its own line here they are sentences in a paragraph, so format it as one.
```suggestion
  // In riscv64, 32-bit FPRs are NaN-boxed to 64-bit FPRs.  In other words, in
  // RI64, when accessing 32-bit FPRs, you are actually accessing the entire
  // register.

  // Capstone distinguishes between 32-bit FPRs and 64-bit FPRs.  So far, other
  // libraries such as Dwarf does not distinguish between the two.  So here
  // f<N>_32 and f<N>_64 are used to handle Capstone registers On the other
  // hand, f<N> are the "actual" FPRs that include both the NaN-boxed f<N>_32
  // and f<N>_64.  f<N>_32 and f<N>_64 are both aliases of f<N>
```

2025-09-03 16:36 UTC, kupsch commented on common/h/registers/riscv64_regs.h
> +   *  Next 16 bits (0x00ff0000) are the register category, GPR/FPR/MMX/...
Wrap the long line, and change x86 categories to to RISC-V:
```suggestion
   *  Next 16 bits (0x0000ff00) are used to distinguish between 32/64 bit
   *                            floating point registers
   *  Next 16 bits (0x00ff0000) are the register category, GPR/FPR/SPR/CSR
```

2025-09-04 02:03 UTC, wxrdnx commented on common/h/registers/riscv64_regs.h
> +  // Unprivileged Vector CSRs, read/write
Done

2025-09-04 02:03 UTC, wxrdnx commented on common/src/registers/MachRegister.C
> +      // linux syscall(2) man page.
DOne

2025-09-04 02:04 UTC, wxrdnx commented on instructionAPI/capstone/riscv64/registers.py
Done

2025-09-04 02:04 UTC, wxrdnx commented on instructionAPI/capstone/riscv64/mnemonics.py
Done

2025-09-04 19:52 UTC, kupsch approved these changes

2025-09-07 20:53 UTC, hainest approved these changes
No test regressions on 18 machines.

Thanks so much for all the effort on handling the many change requests!

2025-09-30 15:52 UTC, merged