make symbol name demangling consistent
dyninst/dyninst pull request #889
Opened 2020-10-13 15:13 UTC by kupsch

Make symbol name demangling consistent between C and C++, between pretty and typed names.  Removes "native compiler" concept (old C++ mangling format used with pgcc).

Fixes #717 
Fixes #872

2020-10-16 01:24 UTC, hainest requested changes

2020-10-16 01:24 UTC, hainest commented on symtabAPI/src/parseStab.C
>     if ( name[0] != '\0' && stabstr[cnt] != ':' )
`std::string` isn't guaranteed to be null-terminated. A better check is `!name.empty()`. I know you didn't write this, but we may as well clean it up while we're here.

2020-10-16 01:24 UTC, hainest commented on common/CMakeLists.txt
> +    src/symbolDemangle.c
Could you remind me why we had to put this in a C-lang file by itself instead of in symbolDemangleWithCache?

2020-10-16 15:01 UTC, kupsch commented on common/CMakeLists.txt
> +  set (C_SRC_LIST ${C_SRC_LIST}
It needed to be a C file as libiberty.h when included in C++, redefines basename in an incompatible way than the definition of basename in string.h:

extern char *basename(const char*);  // libiberty.h
extern "C++" const char *basename(const char*);   //string.h

2020-10-16 20:49 UTC, hainest approved these changes

2020-10-16 20:50 UTC, hainest commented
https://bottle.cs.wisc.edu/search?dyninst_branch=PR889&status=OK

I'm seeing regressions in test5_9 on zeroah and coriander. I'm not sure what happened on cayenne.

2020-10-16 21:04 UTC, kupsch commented
Do you have time for teams call to help me understand the testsuite?

Thanks,
Jim

On 10/16/20 3:50 PM, Tim Haines wrote:
> https://bottle.cs.wisc.edu/search?dyninst_branch=PR889&status=OK 
> <https://bottle.cs.wisc.edu/search?dyninst_branch=PR889&status=OK>
> 
> I'm seeing regressions in test5_9 on zeroah and coriander. I'm not sure 
> what happened on cayenne.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/dyninst/dyninst/pull/889#issuecomment-710609868>, or 
> unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AFIDUNGHXSWUU2ATASLKCHTSLCW2RANCNFSM4SPCIYUA>.
>

2020-10-16 22:19 UTC, hainest commented
I'm on Teams now, if you have time.

Looking at the log, we are getting these asserts firing on zeroah

    test_driver: /home/tim/paradyn/DEBY5hpE/dyninst/src/parseAPI/src/Function.C:509:
    void Dyninst::ParseAPI::Function::set_retstatus(Dyninst::ParseAPI::FuncReturnStatus):
    Assertion `!(_rs == NORETURN && rs == RETURN)' failed.
    
    test_driver: /home/tim/paradyn/DEBY5hpE/dyninst/src/symtabAPI/src/emitElfStatic-aarch64.C:169: 
    void Dyninst::SymtabAPI::emitElfStatic::getExcludedSymbolNames(std::set<std::__cxx11::basic_string<char> >&):
    Assertion `!EMIT_STATIC_ASSERT' failed.

Oddly, I'm not seeing those error messages on coriander. I would say let's focus on zeroah first, then we'll see what happened on coriander.

2020-10-20 21:16 UTC, kupsch commented
@hainest, the demangle branch now passes the testsuite on coriander. You can test the other platforms now.

2020-10-20 21:40 UTC, hainest commented
@kupsch  Could you rebase this on master?

2020-10-21 19:47 UTC, kupsch commented
@hainest branch is rebased to master.  Testing can begin.

2020-10-21 20:55 UTC, hainest commented
https://bottle.cs.wisc.edu/search?dyninst_branch=PR889&since_date=2020-10-21

Looking good so far. I need to install libiberty on the rest of my test systems before I can proceed further. I will let you know what I find.

2020-10-22 04:05 UTC, hainest commented
LGTM. You can merge when you are ready.

2020-10-22 13:26 UTC, merged